package com.siupay.openapi.v1.persistence.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RechargeOrderDetailsDOExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    public RechargeOrderDetailsDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_order_details
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyIsNull() {
            addCriterion("fiat_currency is null");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyIsNotNull() {
            addCriterion("fiat_currency is not null");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyEqualTo(String value) {
            addCriterion("fiat_currency =", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyNotEqualTo(String value) {
            addCriterion("fiat_currency <>", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyGreaterThan(String value) {
            addCriterion("fiat_currency >", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("fiat_currency >=", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyLessThan(String value) {
            addCriterion("fiat_currency <", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyLessThanOrEqualTo(String value) {
            addCriterion("fiat_currency <=", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyLike(String value) {
            addCriterion("fiat_currency like", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyNotLike(String value) {
            addCriterion("fiat_currency not like", value, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyIn(List<String> values) {
            addCriterion("fiat_currency in", values, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyNotIn(List<String> values) {
            addCriterion("fiat_currency not in", values, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyBetween(String value1, String value2) {
            addCriterion("fiat_currency between", value1, value2, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andFiatCurrencyNotBetween(String value1, String value2) {
            addCriterion("fiat_currency not between", value1, value2, "fiatCurrency");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountIsNull() {
            addCriterion("recharge_amount is null");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountIsNotNull() {
            addCriterion("recharge_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountEqualTo(BigDecimal value) {
            addCriterion("recharge_amount =", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountNotEqualTo(BigDecimal value) {
            addCriterion("recharge_amount <>", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountGreaterThan(BigDecimal value) {
            addCriterion("recharge_amount >", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("recharge_amount >=", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountLessThan(BigDecimal value) {
            addCriterion("recharge_amount <", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("recharge_amount <=", value, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountIn(List<BigDecimal> values) {
            addCriterion("recharge_amount in", values, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountNotIn(List<BigDecimal> values) {
            addCriterion("recharge_amount not in", values, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recharge_amount between", value1, value2, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andRechargeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("recharge_amount not between", value1, value2, "rechargeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("channel_name =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("channel_name <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("channel_name like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("channel_name not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("channel_name in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIsNull() {
            addCriterion("channel_type is null");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIsNotNull() {
            addCriterion("channel_type is not null");
            return (Criteria) this;
        }

        public Criteria andChannelTypeEqualTo(String value) {
            addCriterion("channel_type =", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotEqualTo(String value) {
            addCriterion("channel_type <>", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeGreaterThan(String value) {
            addCriterion("channel_type >", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeGreaterThanOrEqualTo(String value) {
            addCriterion("channel_type >=", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLessThan(String value) {
            addCriterion("channel_type <", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLessThanOrEqualTo(String value) {
            addCriterion("channel_type <=", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeLike(String value) {
            addCriterion("channel_type like", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotLike(String value) {
            addCriterion("channel_type not like", value, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeIn(List<String> values) {
            addCriterion("channel_type in", values, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotIn(List<String> values) {
            addCriterion("channel_type not in", values, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeBetween(String value1, String value2) {
            addCriterion("channel_type between", value1, value2, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelTypeNotBetween(String value1, String value2) {
            addCriterion("channel_type not between", value1, value2, "channelType");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdIsNull() {
            addCriterion("channel_biz_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdIsNotNull() {
            addCriterion("channel_biz_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdEqualTo(String value) {
            addCriterion("channel_biz_id =", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdNotEqualTo(String value) {
            addCriterion("channel_biz_id <>", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdGreaterThan(String value) {
            addCriterion("channel_biz_id >", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdGreaterThanOrEqualTo(String value) {
            addCriterion("channel_biz_id >=", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdLessThan(String value) {
            addCriterion("channel_biz_id <", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdLessThanOrEqualTo(String value) {
            addCriterion("channel_biz_id <=", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdLike(String value) {
            addCriterion("channel_biz_id like", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdNotLike(String value) {
            addCriterion("channel_biz_id not like", value, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdIn(List<String> values) {
            addCriterion("channel_biz_id in", values, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdNotIn(List<String> values) {
            addCriterion("channel_biz_id not in", values, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdBetween(String value1, String value2) {
            addCriterion("channel_biz_id between", value1, value2, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelBizIdNotBetween(String value1, String value2) {
            addCriterion("channel_biz_id not between", value1, value2, "channelBizId");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusIsNull() {
            addCriterion("channel_recharge_status is null");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusIsNotNull() {
            addCriterion("channel_recharge_status is not null");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusEqualTo(Integer value) {
            addCriterion("channel_recharge_status =", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusNotEqualTo(Integer value) {
            addCriterion("channel_recharge_status <>", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusGreaterThan(Integer value) {
            addCriterion("channel_recharge_status >", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_recharge_status >=", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusLessThan(Integer value) {
            addCriterion("channel_recharge_status <", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("channel_recharge_status <=", value, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusIn(List<Integer> values) {
            addCriterion("channel_recharge_status in", values, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusNotIn(List<Integer> values) {
            addCriterion("channel_recharge_status not in", values, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusBetween(Integer value1, Integer value2) {
            addCriterion("channel_recharge_status between", value1, value2, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelRechargeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_recharge_status not between", value1, value2, "channelRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeIsNull() {
            addCriterion("channel_status_time is null");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeIsNotNull() {
            addCriterion("channel_status_time is not null");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeEqualTo(Date value) {
            addCriterion("channel_status_time =", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeNotEqualTo(Date value) {
            addCriterion("channel_status_time <>", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeGreaterThan(Date value) {
            addCriterion("channel_status_time >", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("channel_status_time >=", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeLessThan(Date value) {
            addCriterion("channel_status_time <", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeLessThanOrEqualTo(Date value) {
            addCriterion("channel_status_time <=", value, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeIn(List<Date> values) {
            addCriterion("channel_status_time in", values, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeNotIn(List<Date> values) {
            addCriterion("channel_status_time not in", values, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeBetween(Date value1, Date value2) {
            addCriterion("channel_status_time between", value1, value2, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusTimeNotBetween(Date value1, Date value2) {
            addCriterion("channel_status_time not between", value1, value2, "channelStatusTime");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescIsNull() {
            addCriterion("channel_status_desc is null");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescIsNotNull() {
            addCriterion("channel_status_desc is not null");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescEqualTo(String value) {
            addCriterion("channel_status_desc =", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescNotEqualTo(String value) {
            addCriterion("channel_status_desc <>", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescGreaterThan(String value) {
            addCriterion("channel_status_desc >", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescGreaterThanOrEqualTo(String value) {
            addCriterion("channel_status_desc >=", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescLessThan(String value) {
            addCriterion("channel_status_desc <", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescLessThanOrEqualTo(String value) {
            addCriterion("channel_status_desc <=", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescLike(String value) {
            addCriterion("channel_status_desc like", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescNotLike(String value) {
            addCriterion("channel_status_desc not like", value, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescIn(List<String> values) {
            addCriterion("channel_status_desc in", values, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescNotIn(List<String> values) {
            addCriterion("channel_status_desc not in", values, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescBetween(String value1, String value2) {
            addCriterion("channel_status_desc between", value1, value2, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelStatusDescNotBetween(String value1, String value2) {
            addCriterion("channel_status_desc not between", value1, value2, "channelStatusDesc");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagIsNull() {
            addCriterion("channel_fee_tag is null");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagIsNotNull() {
            addCriterion("channel_fee_tag is not null");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagEqualTo(String value) {
            addCriterion("channel_fee_tag =", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagNotEqualTo(String value) {
            addCriterion("channel_fee_tag <>", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagGreaterThan(String value) {
            addCriterion("channel_fee_tag >", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagGreaterThanOrEqualTo(String value) {
            addCriterion("channel_fee_tag >=", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagLessThan(String value) {
            addCriterion("channel_fee_tag <", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagLessThanOrEqualTo(String value) {
            addCriterion("channel_fee_tag <=", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagLike(String value) {
            addCriterion("channel_fee_tag like", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagNotLike(String value) {
            addCriterion("channel_fee_tag not like", value, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagIn(List<String> values) {
            addCriterion("channel_fee_tag in", values, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagNotIn(List<String> values) {
            addCriterion("channel_fee_tag not in", values, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagBetween(String value1, String value2) {
            addCriterion("channel_fee_tag between", value1, value2, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeTagNotBetween(String value1, String value2) {
            addCriterion("channel_fee_tag not between", value1, value2, "channelFeeTag");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountIsNull() {
            addCriterion("channel_fee_amount is null");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountIsNotNull() {
            addCriterion("channel_fee_amount is not null");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountEqualTo(BigDecimal value) {
            addCriterion("channel_fee_amount =", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountNotEqualTo(BigDecimal value) {
            addCriterion("channel_fee_amount <>", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountGreaterThan(BigDecimal value) {
            addCriterion("channel_fee_amount >", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_fee_amount >=", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountLessThan(BigDecimal value) {
            addCriterion("channel_fee_amount <", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_fee_amount <=", value, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountIn(List<BigDecimal> values) {
            addCriterion("channel_fee_amount in", values, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountNotIn(List<BigDecimal> values) {
            addCriterion("channel_fee_amount not in", values, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_fee_amount between", value1, value2, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelFeeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_fee_amount not between", value1, value2, "channelFeeAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountIsNull() {
            addCriterion("channel_rechargeback_amount is null");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountIsNotNull() {
            addCriterion("channel_rechargeback_amount is not null");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountEqualTo(BigDecimal value) {
            addCriterion("channel_rechargeback_amount =", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountNotEqualTo(BigDecimal value) {
            addCriterion("channel_rechargeback_amount <>", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountGreaterThan(BigDecimal value) {
            addCriterion("channel_rechargeback_amount >", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_rechargeback_amount >=", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountLessThan(BigDecimal value) {
            addCriterion("channel_rechargeback_amount <", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("channel_rechargeback_amount <=", value, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountIn(List<BigDecimal> values) {
            addCriterion("channel_rechargeback_amount in", values, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountNotIn(List<BigDecimal> values) {
            addCriterion("channel_rechargeback_amount not in", values, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_rechargeback_amount between", value1, value2, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andChannelRechargebackAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("channel_rechargeback_amount not between", value1, value2, "channelRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagIsNull() {
            addCriterion("platform_fee_tag is null");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagIsNotNull() {
            addCriterion("platform_fee_tag is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagEqualTo(String value) {
            addCriterion("platform_fee_tag =", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagNotEqualTo(String value) {
            addCriterion("platform_fee_tag <>", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagGreaterThan(String value) {
            addCriterion("platform_fee_tag >", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagGreaterThanOrEqualTo(String value) {
            addCriterion("platform_fee_tag >=", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagLessThan(String value) {
            addCriterion("platform_fee_tag <", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagLessThanOrEqualTo(String value) {
            addCriterion("platform_fee_tag <=", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagLike(String value) {
            addCriterion("platform_fee_tag like", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagNotLike(String value) {
            addCriterion("platform_fee_tag not like", value, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagIn(List<String> values) {
            addCriterion("platform_fee_tag in", values, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagNotIn(List<String> values) {
            addCriterion("platform_fee_tag not in", values, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagBetween(String value1, String value2) {
            addCriterion("platform_fee_tag between", value1, value2, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeTagNotBetween(String value1, String value2) {
            addCriterion("platform_fee_tag not between", value1, value2, "platformFeeTag");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountIsNull() {
            addCriterion("platform_fee_amount is null");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountIsNotNull() {
            addCriterion("platform_fee_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountEqualTo(BigDecimal value) {
            addCriterion("platform_fee_amount =", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountNotEqualTo(BigDecimal value) {
            addCriterion("platform_fee_amount <>", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountGreaterThan(BigDecimal value) {
            addCriterion("platform_fee_amount >", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("platform_fee_amount >=", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountLessThan(BigDecimal value) {
            addCriterion("platform_fee_amount <", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("platform_fee_amount <=", value, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountIn(List<BigDecimal> values) {
            addCriterion("platform_fee_amount in", values, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountNotIn(List<BigDecimal> values) {
            addCriterion("platform_fee_amount not in", values, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("platform_fee_amount between", value1, value2, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andPlatformFeeAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("platform_fee_amount not between", value1, value2, "platformFeeAmount");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdIsNull() {
            addCriterion("account_biz_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdIsNotNull() {
            addCriterion("account_biz_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdEqualTo(String value) {
            addCriterion("account_biz_id =", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdNotEqualTo(String value) {
            addCriterion("account_biz_id <>", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdGreaterThan(String value) {
            addCriterion("account_biz_id >", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_biz_id >=", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdLessThan(String value) {
            addCriterion("account_biz_id <", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdLessThanOrEqualTo(String value) {
            addCriterion("account_biz_id <=", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdLike(String value) {
            addCriterion("account_biz_id like", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdNotLike(String value) {
            addCriterion("account_biz_id not like", value, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdIn(List<String> values) {
            addCriterion("account_biz_id in", values, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdNotIn(List<String> values) {
            addCriterion("account_biz_id not in", values, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdBetween(String value1, String value2) {
            addCriterion("account_biz_id between", value1, value2, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountBizIdNotBetween(String value1, String value2) {
            addCriterion("account_biz_id not between", value1, value2, "accountBizId");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceIsNull() {
            addCriterion("account_user_balance is null");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceIsNotNull() {
            addCriterion("account_user_balance is not null");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceEqualTo(BigDecimal value) {
            addCriterion("account_user_balance =", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceNotEqualTo(BigDecimal value) {
            addCriterion("account_user_balance <>", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceGreaterThan(BigDecimal value) {
            addCriterion("account_user_balance >", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("account_user_balance >=", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceLessThan(BigDecimal value) {
            addCriterion("account_user_balance <", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("account_user_balance <=", value, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceIn(List<BigDecimal> values) {
            addCriterion("account_user_balance in", values, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceNotIn(List<BigDecimal> values) {
            addCriterion("account_user_balance not in", values, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("account_user_balance between", value1, value2, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountUserBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("account_user_balance not between", value1, value2, "accountUserBalance");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountIsNull() {
            addCriterion("account_rechargeback_amount is null");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountIsNotNull() {
            addCriterion("account_rechargeback_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountEqualTo(BigDecimal value) {
            addCriterion("account_rechargeback_amount =", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountNotEqualTo(BigDecimal value) {
            addCriterion("account_rechargeback_amount <>", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountGreaterThan(BigDecimal value) {
            addCriterion("account_rechargeback_amount >", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("account_rechargeback_amount >=", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountLessThan(BigDecimal value) {
            addCriterion("account_rechargeback_amount <", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("account_rechargeback_amount <=", value, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountIn(List<BigDecimal> values) {
            addCriterion("account_rechargeback_amount in", values, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountNotIn(List<BigDecimal> values) {
            addCriterion("account_rechargeback_amount not in", values, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("account_rechargeback_amount between", value1, value2, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargebackAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("account_rechargeback_amount not between", value1, value2, "accountRechargebackAmount");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusIsNull() {
            addCriterion("account_recharge_status is null");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusIsNotNull() {
            addCriterion("account_recharge_status is not null");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusEqualTo(Integer value) {
            addCriterion("account_recharge_status =", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusNotEqualTo(Integer value) {
            addCriterion("account_recharge_status <>", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusGreaterThan(Integer value) {
            addCriterion("account_recharge_status >", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_recharge_status >=", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusLessThan(Integer value) {
            addCriterion("account_recharge_status <", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusLessThanOrEqualTo(Integer value) {
            addCriterion("account_recharge_status <=", value, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusIn(List<Integer> values) {
            addCriterion("account_recharge_status in", values, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusNotIn(List<Integer> values) {
            addCriterion("account_recharge_status not in", values, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusBetween(Integer value1, Integer value2) {
            addCriterion("account_recharge_status between", value1, value2, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountRechargeStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("account_recharge_status not between", value1, value2, "accountRechargeStatus");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeIsNull() {
            addCriterion("account_status_time is null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeIsNotNull() {
            addCriterion("account_status_time is not null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeEqualTo(Date value) {
            addCriterion("account_status_time =", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeNotEqualTo(Date value) {
            addCriterion("account_status_time <>", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeGreaterThan(Date value) {
            addCriterion("account_status_time >", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("account_status_time >=", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeLessThan(Date value) {
            addCriterion("account_status_time <", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeLessThanOrEqualTo(Date value) {
            addCriterion("account_status_time <=", value, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeIn(List<Date> values) {
            addCriterion("account_status_time in", values, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeNotIn(List<Date> values) {
            addCriterion("account_status_time not in", values, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeBetween(Date value1, Date value2) {
            addCriterion("account_status_time between", value1, value2, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusTimeNotBetween(Date value1, Date value2) {
            addCriterion("account_status_time not between", value1, value2, "accountStatusTime");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescIsNull() {
            addCriterion("account_status_desc is null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescIsNotNull() {
            addCriterion("account_status_desc is not null");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescEqualTo(String value) {
            addCriterion("account_status_desc =", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescNotEqualTo(String value) {
            addCriterion("account_status_desc <>", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescGreaterThan(String value) {
            addCriterion("account_status_desc >", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescGreaterThanOrEqualTo(String value) {
            addCriterion("account_status_desc >=", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescLessThan(String value) {
            addCriterion("account_status_desc <", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescLessThanOrEqualTo(String value) {
            addCriterion("account_status_desc <=", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescLike(String value) {
            addCriterion("account_status_desc like", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescNotLike(String value) {
            addCriterion("account_status_desc not like", value, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescIn(List<String> values) {
            addCriterion("account_status_desc in", values, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescNotIn(List<String> values) {
            addCriterion("account_status_desc not in", values, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescBetween(String value1, String value2) {
            addCriterion("account_status_desc between", value1, value2, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andAccountStatusDescNotBetween(String value1, String value2) {
            addCriterion("account_status_desc not between", value1, value2, "accountStatusDesc");
            return (Criteria) this;
        }

        public Criteria andOtherAmountIsNull() {
            addCriterion("other_amount is null");
            return (Criteria) this;
        }

        public Criteria andOtherAmountIsNotNull() {
            addCriterion("other_amount is not null");
            return (Criteria) this;
        }

        public Criteria andOtherAmountEqualTo(BigDecimal value) {
            addCriterion("other_amount =", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountNotEqualTo(BigDecimal value) {
            addCriterion("other_amount <>", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountGreaterThan(BigDecimal value) {
            addCriterion("other_amount >", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("other_amount >=", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountLessThan(BigDecimal value) {
            addCriterion("other_amount <", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("other_amount <=", value, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountIn(List<BigDecimal> values) {
            addCriterion("other_amount in", values, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountNotIn(List<BigDecimal> values) {
            addCriterion("other_amount not in", values, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_amount between", value1, value2, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_amount not between", value1, value2, "otherAmount");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityIsNull() {
            addCriterion("other_quantity is null");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityIsNotNull() {
            addCriterion("other_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityEqualTo(BigDecimal value) {
            addCriterion("other_quantity =", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityNotEqualTo(BigDecimal value) {
            addCriterion("other_quantity <>", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityGreaterThan(BigDecimal value) {
            addCriterion("other_quantity >", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("other_quantity >=", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityLessThan(BigDecimal value) {
            addCriterion("other_quantity <", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("other_quantity <=", value, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityIn(List<BigDecimal> values) {
            addCriterion("other_quantity in", values, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityNotIn(List<BigDecimal> values) {
            addCriterion("other_quantity not in", values, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_quantity between", value1, value2, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andOtherQuantityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("other_quantity not between", value1, value2, "otherQuantity");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusIsNull() {
            addCriterion("details_status is null");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusIsNotNull() {
            addCriterion("details_status is not null");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusEqualTo(Integer value) {
            addCriterion("details_status =", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusNotEqualTo(Integer value) {
            addCriterion("details_status <>", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusGreaterThan(Integer value) {
            addCriterion("details_status >", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("details_status >=", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusLessThan(Integer value) {
            addCriterion("details_status <", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusLessThanOrEqualTo(Integer value) {
            addCriterion("details_status <=", value, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusIn(List<Integer> values) {
            addCriterion("details_status in", values, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusNotIn(List<Integer> values) {
            addCriterion("details_status not in", values, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusBetween(Integer value1, Integer value2) {
            addCriterion("details_status between", value1, value2, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andDetailsStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("details_status not between", value1, value2, "detailsStatus");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIsNull() {
            addCriterion("order_source is null");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIsNotNull() {
            addCriterion("order_source is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSourceEqualTo(String value) {
            addCriterion("order_source =", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceNotEqualTo(String value) {
            addCriterion("order_source <>", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceGreaterThan(String value) {
            addCriterion("order_source >", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceGreaterThanOrEqualTo(String value) {
            addCriterion("order_source >=", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceLessThan(String value) {
            addCriterion("order_source <", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceLessThanOrEqualTo(String value) {
            addCriterion("order_source <=", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceLike(String value) {
            addCriterion("order_source like", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceNotLike(String value) {
            addCriterion("order_source not like", value, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIn(List<String> values) {
            addCriterion("order_source in", values, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceNotIn(List<String> values) {
            addCriterion("order_source not in", values, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceBetween(String value1, String value2) {
            addCriterion("order_source between", value1, value2, "orderSource");
            return (Criteria) this;
        }

        public Criteria andOrderSourceNotBetween(String value1, String value2) {
            addCriterion("order_source not between", value1, value2, "orderSource");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNull() {
            addCriterion("card_id is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("card_id is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("card_id =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("card_id <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("card_id >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("card_id >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("card_id <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("card_id <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("card_id like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("card_id not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List<String> values) {
            addCriterion("card_id in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List<String> values) {
            addCriterion("card_id not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("card_id between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("card_id not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andClientFromIsNull() {
            addCriterion("client_from is null");
            return (Criteria) this;
        }

        public Criteria andClientFromIsNotNull() {
            addCriterion("client_from is not null");
            return (Criteria) this;
        }

        public Criteria andClientFromEqualTo(String value) {
            addCriterion("client_from =", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromNotEqualTo(String value) {
            addCriterion("client_from <>", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromGreaterThan(String value) {
            addCriterion("client_from >", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromGreaterThanOrEqualTo(String value) {
            addCriterion("client_from >=", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromLessThan(String value) {
            addCriterion("client_from <", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromLessThanOrEqualTo(String value) {
            addCriterion("client_from <=", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromLike(String value) {
            addCriterion("client_from like", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromNotLike(String value) {
            addCriterion("client_from not like", value, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromIn(List<String> values) {
            addCriterion("client_from in", values, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromNotIn(List<String> values) {
            addCriterion("client_from not in", values, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromBetween(String value1, String value2) {
            addCriterion("client_from between", value1, value2, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andClientFromNotBetween(String value1, String value2) {
            addCriterion("client_from not between", value1, value2, "clientFrom");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_order_details
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recharge_order_details
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}